# Generated by Django 5.1.5 on 2025-02-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadofacturas',
            options={'managed': False},
        ),
    ]
