# Generated by Django 5.1.5 on 2025-01-31 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadostraslados',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='transportadoras',
            options={'permissions': [('generar_guias', 'generar_guias'), ('ver_traslados', 'ver_traslados')]},
        ),
        migrations.AlterModelOptions(
            name='traslados',
            options={'managed': False},
        ),
    ]
